### ISSUE TITLE
Error when obtaining a list with zero devices

### ISSUE THREAD

**Issue by NikolasPapas** [GeorgiosGoniotakis/BluetoothWrapper#10]
![capturelibrary](https://user-images.githubusercontent.com/16654291/31771508-12f053b2-b4e5-11e7-9ed2-d24e826b16c5.PNG)
![capture](https://user-images.githubusercontent.com/16654291/31771506-0c58e384-b4e5-11e7-8b56-d0f98eb5d639.PNG)

**Comment by GeorgiosGoniotakis** [comment]
Because of the inability to mock some Bluetooth-related methods, it was not possible to develop unit tests for this method. This is going to be patched along with other bug fixes in the upcoming version 1.3. Thanks!
